<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./src/assets/low_poly_chess_-_rook/scene.gltf --types --transform
Author: marcelo.medeirossilva (https://sketchfab.com/marcelo.medeirossilva)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-chess-rook-cbd416e785f64648bff3675fd45b3594
Title: Low Poly Chess - Rook
-->

<script lang="ts">
  import { T, forwardEventHandlers, type Events, type Props, type Slots } from '@threlte/core';
  import { useGltf } from '@threlte/extras';
  import type * as THREE from 'three';
  import { Group } from 'three';

  type $$Props = Props<THREE.Group> & { color: string | undefined };
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();
  export let color: string | undefined = undefined;

  type GLTFResult = {
    nodes: {
      Chess_Rook_0: THREE.Mesh;
    };
    materials: {
      Root: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>('/rook.glb', { useDraco: true });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
      <T.Mesh
        scale={[1, 1, 1.2]}
        geometry={gltf.nodes.Chess_Rook_0.geometry}
        position={[0, 0, 2.73]}
      >
        <T.MeshBasicMaterial
          args={[
            {
              color: color,
              opacity: 0.9,
              transparent: true,
            },
          ]}
        />
      </T.Mesh>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
